title: "Posts"
description: "Retours d'expérience tech"
author:
  name: "Sébastien Prunier"

url: "https://sebprunier.github.io"
baseurl: "/posts"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Build
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Tags
tag_archive:
  type: liquid
  path: /tags/

# Layout par défaut pour tous les posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      show_date: true

include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
